def draw_mall():
    print("                 ___                 ")
    print("                (   )                ")
    print("        _______(_____)_______        ")
    print("       |         THE         |       ")
    print("       |      M  A  L  L     |       ")
    print("       |                     |       ")
    print("       |          /\         |       ")
    print("       |          \/         |       ")
    print("       |                     |       ")
    print("       |         _____       |       ")
    print("       |        |  |  |      |       ")
    print("       |________|__|__|______|       ")
    print("                                     ")
    return